### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [waruqi/tbox#15]
Would you like to [replace any double quotes](https://github.com/waruqi/tbox/blob/57bd0ac327092a4a44e01bd224d55b45ed96e984/src/tbox/tbox.h#L26 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by waruqi** [comment]
I uses double quotes for including all tbox headers which will be searched first, and only uses the relative path.

But  I will use angle brackets if want to include all system headers.

**Comment by elfring** [comment]
How do you think about to [take another look at corresponding implementation details](https://github.com/waruqi/tbox/issues/2 "Update for inclusion style?")?
