### ISSUE TITLE
macOS下无法编译

### ISSUE THREAD

**Issue by canmor** [waruqi/tbox#21]
XMake v1.0.4.201609061812, The Automatic Cross-platform Build Tool
Copyright (C) 2015-2016 Ruki Wang, tboox.org
Copyright (C) 2005-2014 Mike Pall, luajit.org

步骤：
1. 执行 xmake

```
$ xmake
```

报错：

```
error: /Users/canmor/workspace/tbox/xmake.lua:2: attempt to call global 'set_project' (a nil value)
```

具体的log: [log.txt](https://github.com/waruqi/tbox/files/456466/log.txt)

**Comment by canmor** [comment]
@waruqi 是否xmake的问题？

**Comment by waruqi** [comment]
xmake版本太老 请更新到v2.0.4再试试

**Comment by canmor** [comment]
更新之后好了，是我太久没brew update了，谢谢😀

**Comment by waruqi** [comment]
不客气
