### ISSUE TITLE
linux－clang compile error

### ISSUE THREAD

**Issue by metalwood** [waruqi/tbox#22]
[21%]: compiling.release src/tbox/libc/string/wcsrchr.c
error: src/tbox/libc/string/strlcpy.c:52:12: error: implicit declaration of function 'strlcpy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return strlcpy(s1, s2, n);
           ^
1 error generated.
make[2]: *** [../3rdparty/tbox/src/tbox-stamp/tbox-build] Error 255
make[1]: *** [3rdparty/CMakeFiles/tbox.dir/all] Error 2
make: *** [all] Error 2

**Comment by waruqi** [comment]
看错误 ，已经 #include <string.h> 了，但是还是没找到 strlcpy的声明，导致编译器警告。。

请确认下，include的搜索路径中，是否有重名string.h导致冲突了。。

或者 可以临时改下，tbox/xmake.lua 将，设置警告级别为 set_warning("none")，禁用 Werror，就可以通过了。。

谢谢
