### ISSUE TITLE
关于分拆各模块的使用

### ISSUE THREAD

**Issue by xsjqqq123** [waruqi/tbox#23]
大神，你好，感谢你的分享。看了您的内存模块介绍，我想将它弄到我将来的项目中，为减少库的体积，我只需你模块中的一小部分，毕竟我不需要数据库、流之类的，这些，都有现成的了。请问下各模块的依赖关系如何？可以使用make而不用xmake搞吗？

**Comment by waruqi** [comment]
您好，大部分模块都是可选依赖，你可以使用xmake进行最小模式编译，禁用所有扩展模块：

```bash
$ xmake f --smallest=y
$ xmake
```

使用make的话，需要先用xmake的makefile插件，生成好makefile，再用make来编译：

```bash
$ xmake project -k makefile
$ make
```

谢谢！
