### ISSUE TITLE
怎么编译Example

### ISSUE THREAD

**Issue by xi2008wang** [waruqi/tbox#25]
新手，
现在下载安装了xmake
下载和build了tbox
但问题是怎么编译Example.c?

**Comment by xi2008wang** [comment]
说一点建议：
1.xmake 虽然实际安装简单，执行一下install，但是README.md里没有看到怎么安装
2.tbox想看看CHANGELOG.md，发现部分乱码。file命令一看，原来文件格式不是utf8， 是ISO-8859 text
3.然后就我提的这个问题，README.md没看到怎么编译

**Comment by waruqi** [comment]
tbox和xmake的README.md都有编译说明，可以仔细看下

tbox和xmake的wiki文档也有具体编译文档，或者可以直接参考文档：[xmake编译文档](https://github.com/waruqi/xmake/wiki/%E7%BC%96%E8%AF%91%E5%B7%A5%E7%A8%8B)

更加详细的xmake使用文档见[wiki](https://github.com/waruqi/xmake/wiki/%E7%9B%AE%E5%BD%95)

一般情况下只需要执行：xmake 就可以进行编译

CHANGELOG的编码问题，我已改成utf-8，请重新打开看下。。

谢谢

**Comment by waruqi** [comment]
tbox的src/demo目录 有各种example，默认执行xmake，都是会编译进去的。。

想要测试这些demo，只需要执行 ：xmake run demo coroutine_http_server 

更多测试用例，可以执行 xmake run demo 看下列举的详细列表

**Comment by xi2008wang** [comment]
xmake的文档我大概浏览了一下，也没看到怎么使用tbox
我的问题是一个d1.c
cat d1.c
#include "tbox/tbox.h"

int main(int argc, char** argv)
{
    // init tbox
    if (!tb_init(tb_null, tb_null)) return 0;

    // trace
    tb_trace_i("hello tbox");

    // wait some time
    getchar();

    // exit tbox
    tb_exit();
    return 0;
}

怎么编译成了一个d1的可执行文件？
➜  build git:(master) ls
console   d1.c      demo      libtbox.a tbox
➜  build git:(master) gcc -static  -ltbox d1.c
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)


是不是一定要写一个xmake.lua
关键问题是xmake.lua包含哪些语句使用tbox库

**Comment by waruqi** [comment]
tbox的具体使用，需要看tbox的wiki文档，可以看下：[tbox使用](https://github.com/waruqi/tbox/wiki/v1.5.x%E7%BC%96%E8%AF%91)

xmake的文档只介绍xmake的使用，包括如何编译，当然编译过程完全适用tbox

而你说的d1的编译问题，是基础的静态库使用和开发问题，跟tbox本身没什么关系

你可以google下，linux的c/c++程序开发，可以用些现有的ide来编译，当然也可以使用xmake，写个xmake.lua来直接编译。。

例如，在空目录下，新建个xmake.lua：
```
target("test")
    set_kind("binary")
    add_files("*.c")
    add_links("tbox")
    add_linkdirs(".")
```

并且把源文件放置到这个目录，执行下编译：xmake 就行了

上述你说的链接失败问题，可以先把-static去掉试试。。
