### ISSUE TITLE
支持MCU吗？？

### ISSUE THREAD

**Issue by Pillar1989** [waruqi/tbox#27]
亲，
    tbox支持MCU吗？？可以在stm32 ，avr这样的单片机上跑么？？

**Comment by waruqi** [comment]
什么系统？如果是linux的话。。应该可以的。。不过我没试过。

**Comment by Pillar1989** [comment]
没有任何系统，纯裸机

**Comment by waruqi** [comment]
默认编译不支持，需要稍微对 src/tbox/platform下 相关平台接口做些修改和适配。。才行。。

**Comment by Pillar1989** [comment]
有相关文档吗？ 另外tbox有实际应用于大批量的产品吗？

**Comment by waruqi** [comment]
[wiki](https://github.com/waruqi/tbox/wiki/%E7%9B%AE%E5%BD%95)上有tbox的一些接口使用文档

目前应用的地方还不是很多，尤其是对于裸机环境的适配，暂时没有文档，需要自己对src/tbox/platform下面的部分接口进行适配，默认检测不到已知环境，这些接口的实现会默认置空。
