### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [waruqi/tbox#3]
I would like to point out that identifiers like "[`__tb_debug__`](https://github.com/waruqi/tbox/blob/0a41b81d1c89da816c6651aca87b1f9a5b9f1f9b/src/tbox/tbox.h#L61)" and "[`__tb_extern_c_enter__`](https://github.com/waruqi/tbox/blob/74939b74f1c209aae21e036277c28e467fb78cfd/src/tbox/platform/platform.h#L65)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by waruqi** [comment]
I known it, but I don't plan to adjust it.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by waruqi** [comment]
Uses a unified prefix: "__tb_xxx" to reduce the probability of conflict.

**Comment by elfring** [comment]
Will a prefix be also sufficient for your source files without [leading underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?
