### ISSUE TITLE
我想问一下大神, 你这个lib用在了哪些方面的项目?

### ISSUE THREAD

**Issue by joostshao** [waruqi/tbox#4]
我想问一下大神, 你这个lib用在了哪些方面的项目?

客户端还是在服务端?

**Comment by waruqi** [comment]
都可以用，看具体需求了。。一般用在客户端居多。。没对服务端的应用做更深入的封装和模块支持。。

主要是提供些类glibc/boost库的部分常用功能，以及跨平台支持。。更高级的应用层封装和模块没有提供。。

**Comment by joostshao** [comment]
服务端这块后期会有什么想法吗? road map ..

**Comment by waruqi** [comment]
目前只提供了 最底层的 asio 跨平台封装。。可以用它来写服务器应用，但是接口比较底层。直接使用不是很方便。。

后期会考虑 对上层 协议 做更进一步的封装。。例如： http、rtsp、rtmp的协议服务器等等。。

tbox的定位主要是跨平台和轻量，所以之后封装服务器模块。。也是走嵌入式路线。。也不会封装的功能很强大。。够用就好。。

但这个是后话，最近没时间封装服务器端哦。。

**Comment by denghongcai** [comment]
能保持现在这样作为一个方便使用的工具类库就挺好的了

**Comment by Matrix-Zhang** [comment]
看了下代码,我还是继续用glib吧...

**Comment by waruqi** [comment]
@denghongcai 

stl里面常用的容器结构、算法还有迭代器支持。。tbox里面都有c实现的。。像 vector、hash_map、hash_set、list、single_list、stack、queue、max/min heap等。。
