### ISSUE TITLE
Tboox.org source

### ISSUE THREAD

**Issue by eatonphil** [waruqi/tbox#6]
Hey! Would it be reasonably to do two things: first, put the tboox.org site on Github so people can help with translating to English (or any other language)?; second, self-host tboox.org using a C web-server written using tbox? I would be very interested in working on either of these two issues!

**Comment by waruqi** [comment]
Thank you for your suggestion, and I will put the tboox.org site on Github in the feature.

Thanks!

**Comment by waruqi** [comment]
I have put the tboox.org site on Github (tboox.github.io).

: )
