### ISSUE TITLE
关于 HN 上的一些 comments

### ISSUE THREAD

**Issue by TongKuo** [waruqi/tbox#7]
你好，

几个小时前我将 TBOX 的项目链接分享到了 Hacker News 上，并收到了[一些 comments](https://news.ycombinator.com/item?id=10989560)，预计可能会持续产生一些新的反馈，虽然我是这条 read 的提交者，但是作为原作者才是最有权处理这些 comments 的。

谢谢你的贡献🍺。

**Comment by waruqi** [comment]
你好

非常感谢你把我的项目放到hackernews上，我会对这些comments进行一些反馈，不过个人英文水平有限，反馈可能不会很及时。请谅解。

谢谢
