### ISSUE TITLE
思路很好啊，特别是内嵌检测

### ISSUE THREAD

**Issue by molixiaoge** [waruqi/tbox#9]
我发现大多数开发者对检测这事重视程度不够，导致写出的代码不稳定。本身业界也没有好的开源方案，自己也想过要弄，希望你这个项目能继续搞下去，造福人类啊.

**Comment by waruqi** [comment]
非常感谢您的支持，这个项目我个人一直在用。。

也会一直维护下去，后续还会实现更多实用的模块和特性，来方便日常开发。

谢谢！
